export const CHOOSE_CATEGORY_ITEM = 'CHOOSE_CATEGORY_ITEM';
export const ADD_REVIEW = 'ADD_REVIEW';
export const CHOOSE_PRODUCT_ITEM = 'CHOOSE_PRODUCT_ITEM';
export const UPDATE_PRODUCT_RESULT = 'UPDATE_PRODUCT_RESULT';

